let products = [
    {
        "id": 1001,
        "title": "Agriculture",
        "description": "Agriculture is the science, art and practice of cultivating plants and livestock.",
        "price": 970,
        "location": "Malta",
        "image": "images/product-Agric.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1002,
        "title": "Basketball",
        "description": "Basketball is a team sport in which two teams, most commonly of five players each, opposing one another on a rectangular court, compete with the primary objective of shooting a basketball.",
        "price": 570,
        "location": "Kano",
        "image": "images/product-bball.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1003,
        "title": "Language",
        "description": "Language, a system of conventional spoken, manual (signed), or written symbols by means of which human beings express themselves.",
        "price": 300,
        "location": "Abuja",
        "image": "images/product-english.jpg",
        "availableInventory": 5, 
        "rating": 2,
    },
    {
        "id": 1004,
        "title": "Football",
        "description":  "Football is a family of team sports that involve, to varying degrees, kicking a ball to score a goal.",
        "price": 230,
        "location": "USA",
        "image": "images/product-footall.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1005,
        "title": "French",
        "description":"French is a Romance language of the Indo-European family. It descended from the Vulgar Latin of the Roman Empire, as did all Romance languages.",
        "price": 160,
        "location": "Abuja",
        "image": "images/product-french.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1006,
        "title": "Geography",
        "description": "Geography is a field of science devoted to the study of the lands, features, inhabitants, and phenomena of the Earth and planets.",
        "price": 170,
        "location": "Malta",
        "image": "images/product-geo.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1007,
        "title": "Martial Art",
        "description": "Martial arts are codified systems and traditions of combat practiced for a number of reasons such as self-defense; military and law enforcement applications.",
        "price": 900,
        "location": "London",
        "image": "images/product-judo.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
    {
        "id": 1008,
        "title": "Mathematics",
        "description": "Mathematics includes the study of such topics as quantity (number theory), structure (algebra), space (geometry), and change (analysis).",
        "price": 190,
        "location": "London",
        "image": "images/product-math.jpg",
        "availableInventory": 5, 
        "rating": 4,
    },
    {
        "id": 1009,
        "title": "Music",
        "description": "Music is the art of arranging sounds in time to produce a composition through the elements of melody, harmony, rhythm, and timbre.",
        "price": 295,
        "location": "Abuja",
        "image": "images/product-music.jpg",
        "availableInventory": 5, 
        "rating": 3,
    },
    {
        "id": 1010,
        "title": "Swimming",
        "description": "Swimming is an individual or team racing sport that requires the use of one's entire body to move through water.",
        "price": 188,
        "location": "Kano",
        "image": "images/product-swim.jpg",
        "availableInventory": 5, 
        "rating": 5,
    },
]